### PR TITLE
Added Lifecycle to ViewModel.

### PR DESCRIPTION
**Pull request by szantogab**
-Made `ViewModel` an abstract class instead of an interface because of the lifecycle methods.
-Also added the primitive pairs of the `toObservable` method of `ObservableField` (Int, Float, Double, Long, Boolean).
-Added `MvvmFragment`.

### CODE REVIEW

**Comment by manas-chaudhari** [comment]
Thank you for contributing.

I have a few comments. Let me know what you think.

Making `ViewModel` abstract would make it compulsory to implement the complete lifecycle. In most cases, a simple activated/deactivated lifecycle works. So, the implementation for binding to the activity lifecycle should be optional.

It is very common for a ViewModel to have child ViewModels. As a child ViewModel can have functionality that depends on lifecycle, it would be necessary to pass lifecycle events. This would add boilerplate.

Few approaches:
1. Create a `Lifecycle` interface. `MvvmActivity` will invoke the events if the `ViewModel` implements `Lifecycle`.
  With this, passing events to children still requires boilerplate.

2. Create an object that captures lifecycle and pass it to the ViewModel as a regular dependency. [`NaviComponent`](https://github.com/trello/navi) can be passed to the ViewModel.
  To pass events to children, we can simply pass the `NaviComponent` instance to the children like any other dependency. Thus, it can also be fulfilled through Dagger. 

I am researching on other implementations for handling lifecycle. As of now, the second approach seems like the way to go. This can be implemented by the consumers without any change in the library. 


Regarding primitive Observables, I think that these are adding unnecessary redundancy.
The mapping between types (which is now one-to-one) would become ambiguous, `ObservableInt` gets converted to `rx.Observable<Integer>`, but when converting back, you get `ObservableField<Integer`.
Is there any significant benefit of using `ObservableBoolean` over `Observable<Boolean>`?

**Comment by szantogab** [comment]
The `NaviComponent` way of delegating lifecycle events to the `ViewModel` really makes sense. This way even `RecyclerView` ViewModels can have their own lifecycle, which is great I guess. Suppose you want modify an item in the RecyclerView. Now its `ViewModel` can handle the whole process by sending a request to a server, and then unsubscribe if it's being destroyed.

**Comment by szantogab** [comment]
As far as primitives are concerned, the only benefit I see is that the primitives can avoid `null`s. Maybe that's not as beneficial as it first seemed.

**Comment by szantogab** [comment]
I ran into an issue with `ObservableField<Boolean>`. When the MvvmActivity's onDestroy runs and sets the `BR.vm` to `null`, and then runs `binding.executePendingTransactions()`, my CheckBox's checked attribute becomes null.

  ```
<CheckBox
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:checked="@={vm.inactive}"
                android:text="@string/inactive" />
```

Obviously vm is null, but because I use `ObservableField<Boolean>`, the whole expression defaults to null as well, causing a crash, because the CheckBox's checked BindingAdapter receives a primitive `boolean`:

```
    @BindingAdapter("android:checked")
    public static void setChecked(CompoundButton view, boolean checked) {
```


So, I guess we can't avoid writing converters for the primitives?!

**Comment by manas-chaudhari** [comment]
Awesome catch 👍 

Can you check if using `ObservableBoolean` fixes this? 
In `{vm.inactive}`, as the `vm` is null, the whole expression should be null irrespective of the type of `inactive`.

When working with `rx.Observable`, `toField()` will return an `ObservableField<Boolean>`. Hence, we'll have to make it work with `ObservableField<Boolean>`.

Another approach is to add a `BindingConversion` that provides default values of primitive types.

```java
@BindingConversion
public static boolean toPrimitiveBoolean(Boolean b) {
    return b != null ? b : false;
}
```

**Comment by szantogab** [comment]
I checked it and it works fine with `ObservableBoolean` with this code:

```
  @NonNull
    public static Observable<Boolean> toObservable(@NonNull final ObservableBoolean field) {
        return Observable.create(new Observable.OnSubscribe<Boolean>() {
            @Override
            public void call(final Subscriber<? super Boolean> subscriber) {
                subscriber.onNext(field.get());
                final OnPropertyChangedCallback callback = new OnPropertyChangedCallback() {
                    @Override
                    public void onPropertyChanged(android.databinding.Observable observable, int i) {
                        subscriber.onNext(field.get());
                    }
                };
                field.addOnPropertyChangedCallback(callback);
                subscriber.add(Subscriptions.create(new Action0() {
                    @Override
                    public void call() {
                        field.removeOnPropertyChangedCallback(callback);
                    }
                }));
            }
        });
    }
```

**Comment by szantogab** [comment]
Also, I found out that your previous lifecycle solution through DataBinding is not working, because when the binding happens, the View has been already attached to the window, so the `onViewAttachedToWindow` callback will never be executed. Therefore I modified it to check if the `View` has been attached to the window or not:

```
    @RequiresApi(api = Build.VERSION_CODES.HONEYCOMB_MR1)
    @BindingAdapter("lifecycle")
    public static void bindLifecycle(View view, final Connectable connectable) {
        View.OnAttachStateChangeListener newListener = null;

        if (connectable != null) {
            newListener = new View.OnAttachStateChangeListener() {
                private Subscription subscription;

                @Override
                public void onViewAttachedToWindow(View v) {
                    subscription = connectable.connect();
                }

                @Override
                public void onViewDetachedFromWindow(View v) {
                    subscription.unsubscribe();
                }
            };

            View.OnAttachStateChangeListener oldValue = ListenerUtil.trackListener(view, newListener, R.id.onAttachStateChangeListener);
            if (oldValue != null) {
                view.removeOnAttachStateChangeListener(oldValue);
            }
        }

        if (newListener != null) {
            if (ViewCompat.isAttachedToWindow(view)) {
                newListener.onViewAttachedToWindow(view);
            }

            view.addOnAttachStateChangeListener(newListener);
        }
    }



```

**Comment by manas-chaudhari** [comment]
@szantogab Closing this pull request. We can continue our discussion on the related issue #27.

**Pull request closed without merging**
